# ─── Stage 1: Install dependencies ───────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_PHONE
ARG NEXT_PUBLIC_PHONE_DISPLAY
ARG NEXT_PUBLIC_BUSINESS_NAME
ARG NEXT_PUBLIC_CITY
ARG NEXT_PUBLIC_STATE
ARG NEXT_PUBLIC_GOOGLE_MAPS_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_EMBED
ARG MONGODB_URI
ARG ADMIN_PASSWORD

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_PHONE=${NEXT_PUBLIC_PHONE}
ENV NEXT_PUBLIC_PHONE_DISPLAY=${NEXT_PUBLIC_PHONE_DISPLAY}
ENV NEXT_PUBLIC_BUSINESS_NAME=${NEXT_PUBLIC_BUSINESS_NAME}
ENV NEXT_PUBLIC_CITY=${NEXT_PUBLIC_CITY}
ENV NEXT_PUBLIC_STATE=${NEXT_PUBLIC_STATE}
ENV NEXT_PUBLIC_GOOGLE_MAPS_URL=${NEXT_PUBLIC_GOOGLE_MAPS_URL}
ENV NEXT_PUBLIC_GOOGLE_MAPS_EMBED=${NEXT_PUBLIC_GOOGLE_MAPS_EMBED}
ENV MONGODB_URI=${MONGODB_URI}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}

COPY package.json package-lock.json* ./
RUN npm ci

# ─── Stage 2: Build ───────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_PHONE
ARG NEXT_PUBLIC_PHONE_DISPLAY
ARG NEXT_PUBLIC_BUSINESS_NAME
ARG NEXT_PUBLIC_CITY
ARG NEXT_PUBLIC_STATE
ARG NEXT_PUBLIC_GOOGLE_MAPS_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_EMBED
ARG MONGODB_URI
ARG ADMIN_PASSWORD

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_PHONE=${NEXT_PUBLIC_PHONE}
ENV NEXT_PUBLIC_PHONE_DISPLAY=${NEXT_PUBLIC_PHONE_DISPLAY}
ENV NEXT_PUBLIC_BUSINESS_NAME=${NEXT_PUBLIC_BUSINESS_NAME}
ENV NEXT_PUBLIC_CITY=${NEXT_PUBLIC_CITY}
ENV NEXT_PUBLIC_STATE=${NEXT_PUBLIC_STATE}
ENV NEXT_PUBLIC_GOOGLE_MAPS_URL=${NEXT_PUBLIC_GOOGLE_MAPS_URL}
ENV NEXT_PUBLIC_GOOGLE_MAPS_EMBED=${NEXT_PUBLIC_GOOGLE_MAPS_EMBED}
ENV MONGODB_URI=${MONGODB_URI}
ENV ADMIN_PASSWORD=${ADMIN_PASSWORD}
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# ─── Stage 3: Production runner ───────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
